import unittest
from pathlib import Path
from unittest.mock import patch

from app.ai_client import _provider_order, enrich_reasons
from app.config import Settings
from app.models import Recommendation


def settings(provider: str, openai_key: str = "", nvidia_key: str = "") -> Settings:
    return Settings(
        data_zip_path=Path("data.zip"),
        as_of_date="2026-09-22",
        max_recommendations=10,
        safety_stock_days=14,
        iek_lead_time_days=18,
        systeme_lead_time_days=14,
        ai_provider=provider,
        ai_max_rows=1,
        openai_api_key=openai_key,
        openai_model="gpt-test",
        nvidia_api_key=nvidia_key,
        nvidia_model="nvidia-test",
        nvidia_base_url="https://example.test/v1",
    )


class AiClientTest(unittest.TestCase):
    def test_auto_provider_order_prefers_openai(self):
        configured = settings("auto", openai_key="openai", nvidia_key="nvidia")

        self.assertEqual(_provider_order(configured), ["openai", "nvidia"])

    def test_auto_provider_falls_back_to_nvidia(self):
        row = Recommendation(
            id="r1",
            sku="SKU-1",
            product_name="Test product",
            supplier="Supplier",
            category="Category",
            stock_qty=1,
            in_transit_qty=0,
            recommended_order_qty=10,
            urgency="soon",
            reason="Template reason",
            avg_daily_demand=1,
            coverage_days=1,
            lead_time_days=14,
            moq=1,
        )
        configured = settings("auto", openai_key="openai", nvidia_key="nvidia")

        with patch(
            "app.ai_client._generate_reason_map",
            side_effect=[{}, {"r1": "This reason was generated by the fallback provider."}],
        ) as generate:
            enriched = enrich_reasons([row], configured)

        self.assertIn("fallback provider", enriched[0].reason)
        self.assertEqual(generate.call_args_list[0].args[2], "openai")
        self.assertEqual(generate.call_args_list[1].args[2], "nvidia")


if __name__ == "__main__":
    unittest.main()
